global:
  resolve_timeout: 5m

route:
  receiver: 'email-team'

receivers:
  - name: 'email-team'
    email_configs:
      - to: 'kdsdesign1@gmail.com'
        from: "$FROM_EMAIL"
        smarthost: "$SMTP_HOST"
        auth_username: "$SMTP_USER"
        auth_password: "$SMTP_PASS"
        require_tls: $SMTP_TLS