"""Constants used across the application."""

CONTAINERS = [
    "infra-default-cadvisor",
    "infra-default-grafana",
    "infra-default-mongo",
    "infra-default-mongo-express",
    "infra-default-mongodb-exporter",
    "infra-default-mysql",
    "infra-default-mysql-exporter",
    "infra-default-node-exporter",
    "infra-default-pgadmin",
    "infra-default-phpmyadmin",
    "infra-default-portainer",
    "infra-default-postgres",
    "infra-default-postgres-exporter",
    "infra-default-prometheus",
    "infra-default-redis",
    "infra-default-redis-exporter",
    "infra-default-redisinsight",
    "infra-default-sonarqube",
]
CONTAINER_PORTS = [
    ("infra-default-cadvisor", 8080),
    ("infra-default-grafana", 3000),
    ("infra-default-mongo", 27017),
    ("infra-default-mongo-express", 8081),
    ("infra-default-mongodb-exporter", 9216),
    ("infra-default-mysql", 3306),
    ("infra-default-mysql-exporter", 9104),
    ("infra-default-node-exporter", 9100),
    ("infra-default-pgadmin", 5050),
    ("infra-default-phpmyadmin", 8082),
    ("infra-default-portainer", 9000),
    ("infra-default-postgres", 5432),
    ("infra-default-postgres-exporter", 9187),
    ("infra-default-prometheus", 9090),
    ("infra-default-redis", 6379),
    ("infra-default-redis-exporter", 9121),
    ("infra-default-redisinsight", 8083),
    ("infra-default-sonarqube", 9001),
]
VOLUMES = [
    "infra-default-mongo_data",
    "infra-default-postgres_data",
    "infra-default-pgadmin-data",
    "infra-default-grafana-storage",
    "infra-default-mysql_data",
    "infra-default-redis_data",
]
CONTAINERS_VOLUMES = {
    "infra-default-mongo": "/data/db",
    "infra-default-postgres": "/var/lib/postgresql/data",
    "infra-default-pgadmin": "/var/lib/pgadmin",
    "infra-default-mysql": "/var/lib/mysql",
    "infra-default-redis": "/data",
}
ESSENTIAL_SERVICES = [
    "infra-default-cadvisor",
    "infra-default-grafana",
    "infra-default-mongo",
    "infra-default-mongo-express",
    "infra-default-mongodb-exporter",
    "infra-default-mysql",
    "infra-default-mysql-exporter",
    "infra-default-node-exporter",
    "infra-default-pgadmin",
    "infra-default-phpmyadmin",
    "infra-default-portainer",
    "infra-default-postgres",
    "infra-default-postgres-exporter",
    "infra-default-prometheus",
    "infra-default-redis",
    "infra-default-redis-exporter",
    "infra-default-redisinsight",
    "infra-default-sonarqube",
]
SERVICES_PORTS: dict[str, int] = {
    "infra-default-mongo": 27017,
    "infra-default-mongo-express": 8081,
    "infra-default-mysql": 3306,
    "infra-default-mysql-exporter": 9104,
    "infra-default-sonarqube": 9000,
    "infra-default-grafana": 3001,
    "infra-default-cadvisor": 8080,
    "infra-default-pgadmin": 8082,
    "infra-default-phpmyadmin": 8088,
    "infra-default-portainer": 9001,
    "infra-default-prometheus": 9090,
    "infra-default-redis": 6379,
    "infra-default-postgres": 5432,
    "infra-default-redisinsight": 8083,
    "infra-default-node-exporter": 9100,
    "infra-default-redis-exporter": 9121,
    "infra-default-mongodb-exporter": 9216,
    "infra-default-postgres-exporter": 9187,
}
